# This contains params to be used by the stages to train or predict

prepare:
  split: 0.20
  seed: 2021

featurize:
  seq_length: 100
  batch_size: 64
  buffer_size: 10000

train:
  embedding_dim: 256
  rnn_units: 1024
  epochs: 30
  optimizer: adam
  verbose: 2
  