# It contains all the configs required in the project

source_data:
  data_dir: data
  data_file: CTBM.raw.xlsx
  sheet_name: Codes

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.csv
  TEST_DATA: test.csv
